PlanAndRide/PlanAndRide.Web/Models/ClubViewModel.cs
using Microsoft.Build.Framework;
using PlanAndRide.BusinessLogic;

namespace PlanAndRide.Web.Models
{
    public class ClubViewModel
    {
        public int Id { get; set; }
        public Club Club { get; }
        public ApplicationUser ApplicationUser { get; set; }
        public string Name { get; set; }
        public string? Description { get; set; }
        public bool IsPrivate { get; set; }

    }   
}

PlanAndRide/PlanAndRide.Web/Controllers/ClubsController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PlanAndRide.BusinessLogic;
using PlanAndRide.Web.Models;

namespace PlanAndRide.Web.Controllers
{
    public class ClubsController : Controller
    {
        private readonly IClubService _clubService;
        private readonly IMapper _mapper;
        private readonly IConfiguration _config;
        // GET: ClubsController
        public ClubsController(IClubService clubService, IMapper mapper, IConfiguration config)
        {
            _clubService = clubService;
            _mapper = mapper;
            _config = config;
        }
        // GET: ClubsController
        [Authorize]
        public async Task<ActionResult> Index()
        {
            var model = new ClubsCollectionViewModel();
            var clubs = await _clubService.GetAll();
            model.Clubs = _mapper.Map<IEnumerable<ClubViewModel>>(clubs);
            return View(model);

            //var rides = await _clubService.GetAll();
            //var model = rides.Select(ride => _mapper.Map<ClubViewModel>(ride));
            //return View(model);
        }

        // GET: ClubsController/Details/5
        [Authorize]
        public async Task<ActionResult> Details(int id)
        {
            var club = await _clubService.Get(id);
            if (club != null)
            {
                return View(_mapper.Map<ClubViewModel>(club));
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: ClubsController/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: ClubsController/Create
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(ClubViewModel model)
        {
            //model.Club.ApplicationUser = new ApplicationUser { Id = 1 };

            ModelState.Remove("Club.User");
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            await _clubService.Add(model.Club);
            return RedirectToAction(nameof(Details), new { Id = model.Club.Id });
        }

        // GET: ClubsController/Edit/5
        [Authorize]
        public async Task<ActionResult> Edit(int id)
        {
            var club = await _clubService.Get(id);
            if (club != null)
            {
                return View(_mapper.Map<ClubViewModel>(club));
            }
            return RedirectToAction(nameof(Index));
        }
        // POST: ClubsController/Edit/5
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, ClubViewModel model)
        {
            ModelState.Remove("Club.User");
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            try
            {
                await _clubService.Update(id, _mapper.Map<Club>(model));
                return RedirectToAction(nameof(Details), new { Id = id });
            }
            catch
            {
                return View();
            }
        }


        // GET: ClubsController/Delete/5
        [Authorize]
        public async Task<ActionResult> Delete(int id)
        {
            var club = await _clubService.Get(id);
            if (club != null)
            {
                return View(_mapper.Map<ClubViewModel>(club));
            }
            return RedirectToAction(nameof(Index));
        }

        // POST: ClubsController/Delete/5
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id, ClubViewModel model)
        {
            await _clubService.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

PlanAndRide/PlanAndRide.Web/Views/Clubs/Create.cshtml
@model ClubViewModel;
@{
    ViewData["Title"] = "Create";

}
<div class="container"> 
<h1>Create</h1>

<h4>Club</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsPrivate" /> Is Private
                </label>
            </div><div class="form-group">
                <input style="display:inline" type="submit" value="Create" class="btn btn-primary red-button" />
                <a class="btn btn-secondary grey-button" asp-action="Index">Cancel</a></div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
</div>

PlanAndRide/PlanAndRide.Web/Views/Clubs/Delete.cshtml
@model ClubViewModel

@{
    ViewData["Title"] = "Delete";
}
<div class="container"> 
<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Club</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsPrivate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsPrivate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger red-button" /> |
        <a class="btn btn-secondary grey-button" asp-action="Index">Cancel</a>
    </form>
</div>
</div>

PlanAndRide/PlanAndRide.Web/Views/Clubs/Details.cshtml
@model ClubViewModel

@{
    ViewData["Title"] = "Details";
    var privacyDisplay = "[Private]";
    if (!Model.IsPrivate)
    {
        privacyDisplay = "[Public]";
    }
}
<div class="container"> 
<h4>Club details</h4>
<h6>@privacyDisplay</h6>
<div>
    @*<h4>Event</h4>*@
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsPrivate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsPrivate)
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-outline-primary red-button" asp-action="Edit" asp-route-id=@Model.Id>Edit</a>
    <a class="btn btn-outline-secondary grey-button" asp-action="Index">Back to events</a>
</div>
</div>

PlanAndRide/PlanAndRide.Web/Views/Clubs/Edit.cshtml
@model ClubViewModel

@{
    ViewData["Title"] = "Edit";
}
<div class="container"> 
<h1>Edit</h1>

<h4>Club</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsPrivate" /> Is Private
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary red-button" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
</div>

PlanAndRide/PlanAndRide.Web/Views/Clubs/Index.cshtml
@model PlanAndRide.Web.Models.ClubsCollectionViewModel

@{
    ViewData["Title"]= "Index";
}
<div class="container"> 
<h1>Clubs</h1>
<p>
     <div class="button" id="button-animation">
            <div id="translate"></div>
            <a class="submit-button" asp-area="" asp-controller="Clubs" asp-action="Create">New Club</a>
        </div>
</p>
<table class="table" id="myTable">
    <thead>
        <tr>
            <th>
                <label asp-for="@Model.Clubs.FirstOrDefault().Name"></label>
            </th>
        </tr>
        <tr>
            <th>
                <label asp-for="@Model.Clubs.FirstOrDefault().Description"></label>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model.Clubs)
        {
            <tr>
                <td>
                    @item.Name
                </td>
                <td>
                    @item.Description
                </td>
                <td>
                    <a class="btn btn-outline-info grey-button" asp-action="Details" asp-route-id="@item.Id">Details</a>
                    <a class="btn btn-outline-primary grey-button" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                    <a class="btn btn-outline-danger grey-button" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>
@section scripts {
    <script> 
       $(document).ready( function () {
    $('#myTable').DataTable();
} );
   </script>
}
</div>